sudo: required

language: go

go:
  - 1.5
  - 1.6
  - 1.6.3
  - tip

services:
  - docker
  - redis

before_install:
  - test -d $GOPATH/bin || mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh

install:
  - export GO15VENDOREXPERIMENT=1
  - glide install

script:
  - go test -v .
