sudo: required

language: go

go:
  - 1.6.x
  - 1.7.x
  - tip

services:
  - docker

before_install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh

script:
  - make test
  - make docker_test
  - make docker_compose_test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt
