sudo: required

language: go

go:
  - 1.5.4
  - 1.6.4
  - 1.7.4
  - tip

services:
  - docker

before_install:
  - curl https://glide.sh/get | sh

install:
  - export GO15VENDOREXPERIMENT=1

script:
  - make test
  - make docker_test
  - make docker_compose_test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt
