language: go

go:
  - 1.5
  - 1.6
  - 1.6.3
  - tip

services:
  - docker

before_install:
  - test -d $GOPATH/bin || mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh

install:
  - export GO15VENDOREXPERIMENT=1
  - make build

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt
