language: go

go:
  - 1.5
  - 1.6
  - 1.6.3
  - tip

services:
  - docker

install:
  - export GO15VENDOREXPERIMENT=1
  - make build

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt
